name: TLSN Plugin Compiler Pipeline

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Replace files with incoming payload using Python
        if: github.event.client_payload != null
        run: |
          echo '${{ toJSON(github.event.client_payload) }}' > payload.json
          python process_payload.py

      - name: Install Extism
        run: |
          curl -O https://raw.githubusercontent.com/extism/js-pdk/main/install.sh
          chmod +x install.sh
          ./install.sh

      - name: Install dependencies and build project
        run: |
          npm install
          npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: wasm-artifact
          path: ./dist/*.wasm
