name: TLSN Plugin Compiler Pipeline

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Replace files with incoming payload
        if: github.event.client_payload != null
        run: |
          echo '${{ toJSON(github.event.client_payload) }}' > payload.json
          
          # Extract and write index.d.ts
          jq -r '.["index.d.ts"]' payload.json | sed 's/\\n/\n/g' > src/index.d.ts
          
          # Extract and write index.ts
          jq -r '.["index.ts"]' payload.json | sed 's/\\n/\n/g' > src/index.ts
          
          # Create utils directory if not exists
          mkdir -p utils
          
          
          # Display the contents for verification
          echo "Contents of src/index.ts:"
          cat src/index.ts
          echo "Contents of src/index.d.ts:"
          cat src/index.d.ts
          echo "Contents of utils/hf.js:"
          cat utils/hf.js

      - name: Install Extism
        run: |
          curl -O https://raw.githubusercontent.com/extism/js-pdk/main/install.sh
          chmod +x install.sh
          ./install.sh

      - name: Install dependencies and build project
        run: |
          npm install
          npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: wasm-artifact
          path: ./dist/*.wasm
